name: Release

on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: MCJack123/ghaction-Generate-Release-Hashes@v4
      with:
        file-name: hashes.txt
    - uses: actions/upload-artifact@v3
      with:
        name: Asset Hashes
        path: hashes.txt